-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-12-06 11:49:33 SE�
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP SEQUENCE cities_id_city_seq;

DROP SEQUENCE countries_id_country_seq;

DROP SEQUENCE credentials_id_credential_seq;

DROP SEQUENCE images_id_image_seq;

DROP SEQUENCE locations_id_location_seq;

DROP SEQUENCE notifications_id_notification;

DROP SEQUENCE organizers_id_organizer_seq;

DROP SEQUENCE reservations_id_reservation;

DROP SEQUENCE roles_id_role_seq;

DROP SEQUENCE room_requests_id_room_request;

DROP SEQUENCE rooms_id_room_seq;

DROP SEQUENCE notification_types_id_notifica;

DROP SEQUENCE audit_log_seq;

DROP VIEW CITIES_V CASCADE CONSTRAINTS 
;

DROP VIEW COUNTRIES_V CASCADE CONSTRAINTS 
;

DROP VIEW CREDENTIALS_V CASCADE CONSTRAINTS 
;

DROP VIEW IMAGES_V CASCADE CONSTRAINTS 
;

DROP VIEW LOCATIONS_V CASCADE CONSTRAINTS 
;

DROP VIEW NOTIFICATIONS_V CASCADE CONSTRAINTS 
;

DROP VIEW ORGANIZERS_V CASCADE CONSTRAINTS 
;

DROP VIEW RESERVATIONS_V CASCADE CONSTRAINTS 
;

DROP VIEW ROLES_V CASCADE CONSTRAINTS 
;

DROP VIEW ROOM_REQUESTS_V CASCADE CONSTRAINTS 
;

DROP VIEW ROOMS_V CASCADE CONSTRAINTS 
;

DROP VIEW USERS_V CASCADE CONSTRAINTS 
;

DROP TABLE cities CASCADE CONSTRAINTS;

DROP TABLE countries CASCADE CONSTRAINTS;

DROP TABLE credentials CASCADE CONSTRAINTS;

DROP TABLE images CASCADE CONSTRAINTS;

DROP TABLE locations CASCADE CONSTRAINTS;

DROP TABLE meeting_rooms CASCADE CONSTRAINTS;

DROP TABLE meeting_rrequests CASCADE CONSTRAINTS;

DROP TABLE notifications CASCADE CONSTRAINTS;

DROP TABLE organizers CASCADE CONSTRAINTS;

DROP TABLE presentation_rooms CASCADE CONSTRAINTS;

DROP TABLE presentation_rrequests CASCADE CONSTRAINTS;

DROP TABLE reservations CASCADE CONSTRAINTS;

DROP TABLE roles CASCADE CONSTRAINTS;

DROP TABLE room_requests CASCADE CONSTRAINTS;

DROP TABLE rooms CASCADE CONSTRAINTS;

DROP TABLE notification_types CASCADE CONSTRAINTS;

DROP TABLE audit_log;


-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cities (
    id_city    NUMBER NOT NULL,
    "name"       VARCHAR2(64) NOT NULL,
    id_country NUMBER NOT NULL
);

ALTER TABLE cities ADD CONSTRAINT cities_pk PRIMARY KEY ( id_city );

ALTER TABLE cities ADD CONSTRAINT city_name_id_country_un UNIQUE ( "name",
                                                                   id_country );

CREATE TABLE countries (
    id_country NUMBER NOT NULL,
    "name"       VARCHAR2(32) NOT NULL
);

ALTER TABLE countries ADD CONSTRAINT countries_pk PRIMARY KEY ( id_country );

ALTER TABLE countries ADD CONSTRAINT countries_name_un UNIQUE ( "name" );

CREATE TABLE credentials (
    id_credential   INTEGER NOT NULL,
    credential_type CHAR(8) NOT NULL,
    "data"            VARCHAR2(256) NOT NULL,
    created_at      TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    id_organizer    NUMBER NOT NULL
);

ALTER TABLE credentials ADD CONSTRAINT credentials_pk PRIMARY KEY ( id_credential );

CREATE TABLE images (
    id_image     NUMBER NOT NULL,
    "data"         BLOB NOT NULL,
    id_organizer NUMBER NOT NULL,
    id_location  NUMBER NOT NULL,
    id_room      NUMBER NOT NULL,
    file_name    VARCHAR2(255) NOT NULL,
    file_suffix  VARCHAR2(10) NOT NULL,
    created_at   DATE  NOT NULL
);

CREATE UNIQUE INDEX image__idx ON
    images (
        id_location
    ASC );

CREATE UNIQUE INDEX image__idxv1 ON
    images (
        id_organizer
    ASC );

CREATE UNIQUE INDEX image__idxv2 ON
    images (
        id_room
    ASC );

ALTER TABLE images ADD CONSTRAINT images_pk PRIMARY KEY ( id_image );

CREATE TABLE locations (
    id_location        NUMBER NOT NULL,
    "name"               VARCHAR2(32) NOT NULL,
    availability_start DATE NOT NULL,
    availability_end   DATE NOT NULL,
    id_city            NUMBER NOT NULL,
    id_organizer       NUMBER NOT NULL
);

ALTER TABLE locations ADD CONSTRAINT locations_pk PRIMARY KEY ( id_location );

ALTER TABLE locations ADD CONSTRAINT location_name_id_city_un UNIQUE ( "name",
                                                                       id_city );

CREATE TABLE meeting_rooms (
    id_room  NUMBER NOT NULL,
    vc_ready CHAR(1) NOT NULL
);

ALTER TABLE meeting_rooms ADD CONSTRAINT meeting_room_pk PRIMARY KEY ( id_room );

CREATE TABLE meeting_rrequests (
    id_room_request NUMBER NOT NULL,
    vc_ready        CHAR(1)
);

ALTER TABLE meeting_rrequests ADD CONSTRAINT meeting_rrequest_pk PRIMARY KEY ( id_room_request );

CREATE TABLE notifications (
    id_notification      INTEGER NOT NULL,
    delivered            CHAR(1) NOT NULL,
    id_organizer         NUMBER NOT NULL,
    id_room_request      NUMBER NOT NULL,
    id_notification_type INTEGER NOT NULL
);

CREATE UNIQUE INDEX notification__idx ON
    notifications (
        id_room_request
    ASC );

ALTER TABLE notifications ADD CONSTRAINT notifications_pk PRIMARY KEY ( id_notification );

CREATE TABLE organizers (
    id_organizer            NUMBER NOT NULL,
    "name"                    VARCHAR2(64) NOT NULL,
    email                   VARCHAR2(320) NOT NULL,
    id_role                 INTEGER,
    id_organizer_substitute NUMBER
);

ALTER TABLE organizers ADD CONSTRAINT organizers_pk PRIMARY KEY ( id_organizer );

ALTER TABLE organizers
    ADD CONSTRAINT organizers_substitute_fk FOREIGN KEY ( id_organizer_substitute )
        REFERENCES organizers ( id_organizer ) ON DELETE SET NULL; 

CREATE TABLE presentation_rooms (
    id_room     NUMBER NOT NULL,
    podium_size NUMBER NOT NULL
);

ALTER TABLE presentation_rooms ADD CONSTRAINT presentation_room_pk PRIMARY KEY ( id_room );

CREATE TABLE presentation_rrequests (
    id_room_request NUMBER NOT NULL,
    podium_size     NUMBER
);

ALTER TABLE presentation_rrequests ADD CONSTRAINT presentation_rrequest_pk PRIMARY KEY ( id_room_request );

CREATE TABLE reservations (
    id_reservation  NUMBER NOT NULL,
    "start"         DATE NOT NULL,
    "end"             DATE NOT NULL,
    id_room         NUMBER NOT NULL,
    id_room_request NUMBER NOT NULL,
    id_organizer    NUMBER NOT NULL
);

-- CREATE UNIQUE INDEX reservation__idx ON reservations ( id_room_request ASC );

ALTER TABLE reservations ADD CONSTRAINT reservations_pk PRIMARY KEY ( id_reservation );

CREATE TABLE roles (
    id_role INTEGER NOT NULL,
    "name"    VARCHAR2(32) NOT NULL
);

ALTER TABLE roles ADD CONSTRAINT roles_pk PRIMARY KEY ( id_role );

CREATE TABLE room_requests (
    id_room_request    NUMBER NOT NULL,
    min_capacity       NUMBER NOT NULL,
    "type"               VARCHAR2(21) NOT NULL,
    reservation_start  DATE NOT NULL,
    reservation_end    DATE,
    reservation_length DATE,
    id_location        NUMBER,
    id_organizer       NUMBER NOT NULL
);

ALTER TABLE room_requests
    ADD CONSTRAINT ch_inh_room_request CHECK ( "type" IN ( 'MEETING_RREQUEST', 'PRESENTATION_RREQUEST', 'ROOM_REQUEST' ) );

ALTER TABLE room_requests ADD CONSTRAINT room_request_pk PRIMARY KEY ( id_room_request );

CREATE TABLE rooms (
    id_room      NUMBER NOT NULL,
    "name"         VARCHAR2(32) NOT NULL,
    capacity     NUMBER NOT NULL,
    "type"         VARCHAR2(17) NOT NULL,
    id_location  NUMBER NOT NULL,
    id_organizer NUMBER NOT NULL
);

CREATE TABLE notification_types (
    id_notification_type INTEGER NOT NULL,
    "code"                 VARCHAR2(20) NOT NULL,
    "name"                 VARCHAR2(50) NOT NULL,
    "description"          VARCHAR2(200)
);

ALTER TABLE notification_types ADD CONSTRAINT notification_type_pk PRIMARY KEY ( id_notification_type );

ALTER TABLE rooms
    ADD CONSTRAINT ch_inh_room CHECK ( "type" IN ( 'MEETING_ROOM', 'PRESENTATION_ROOM', 'ROOM' ) );

ALTER TABLE rooms ADD CONSTRAINT room_pk PRIMARY KEY ( id_room ) ;

ALTER TABLE rooms ADD CONSTRAINT rooms_name_un UNIQUE ( "name" );

ALTER TABLE cities
    ADD CONSTRAINT city_country_fk FOREIGN KEY ( id_country )
        REFERENCES countries ( id_country ) ON DELETE CASCADE;

ALTER TABLE credentials
    ADD CONSTRAINT credential_organizers_fk FOREIGN KEY ( id_organizer )
        REFERENCES organizers ( id_organizer ) ON DELETE CASCADE;

ALTER TABLE images
    ADD CONSTRAINT images_location_fk FOREIGN KEY ( id_location )
        REFERENCES locations ( id_location ) ON DELETE CASCADE;

ALTER TABLE images
    ADD CONSTRAINT images_organizers_fk FOREIGN KEY ( id_organizer )
        REFERENCES organizers ( id_organizer ) ON DELETE CASCADE;

ALTER TABLE images
    ADD CONSTRAINT images_room_fk FOREIGN KEY ( id_room )
        REFERENCES rooms ( id_room ) ON DELETE CASCADE;

ALTER TABLE locations
    ADD CONSTRAINT location_city_fk FOREIGN KEY ( id_city )
        REFERENCES cities ( id_city ) ON DELETE CASCADE;

ALTER TABLE locations
    ADD CONSTRAINT location_organizers_fk FOREIGN KEY ( id_organizer )
        REFERENCES organizers ( id_organizer ) ON DELETE CASCADE;

ALTER TABLE meeting_rooms
    ADD CONSTRAINT meeting_room_room_fk FOREIGN KEY ( id_room )
        REFERENCES rooms ( id_room ) ON DELETE CASCADE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE meeting_rrequests
    ADD CONSTRAINT meeting_rrequest_fk FOREIGN KEY ( id_room_request )
        REFERENCES room_requests ( id_room_request ) ON DELETE CASCADE;

ALTER TABLE notifications
    ADD CONSTRAINT notification_type_fk FOREIGN KEY ( id_notification_type )
        REFERENCES notification_types ( id_notification_type );

ALTER TABLE notifications
    ADD CONSTRAINT notification_organizers_fk FOREIGN KEY ( id_organizer )
        REFERENCES organizers ( id_organizer ) ON DELETE CASCADE;

ALTER TABLE notifications
    ADD CONSTRAINT notification_room_request_fk FOREIGN KEY ( id_room_request )
        REFERENCES room_requests ( id_room_request ) ON DELETE CASCADE;

ALTER TABLE organizers
    ADD CONSTRAINT organizers_role_fk FOREIGN KEY ( id_role )
        REFERENCES roles ( id_role ) ON DELETE CASCADE;

ALTER TABLE presentation_rooms
    ADD CONSTRAINT presentation_room_room_fk FOREIGN KEY ( id_room )
        REFERENCES rooms ( id_room ) ON DELETE CASCADE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE presentation_rrequests
    ADD CONSTRAINT presentation_rrequest_fk FOREIGN KEY ( id_room_request )
        REFERENCES room_requests ( id_room_request ) ON DELETE CASCADE;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_organizers_fk FOREIGN KEY ( id_organizer )
        REFERENCES organizers ( id_organizer ) ON DELETE CASCADE;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_room_fk FOREIGN KEY ( id_room )
        REFERENCES rooms ( id_room ) ON DELETE CASCADE;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_room_request_fk FOREIGN KEY ( id_room_request )
        REFERENCES room_requests ( id_room_request )
            ON DELETE CASCADE;

ALTER TABLE rooms
    ADD CONSTRAINT room_location_fk FOREIGN KEY ( id_location )
        REFERENCES locations ( id_location ) ON DELETE CASCADE;

ALTER TABLE rooms
    ADD CONSTRAINT room_organizers_fk FOREIGN KEY ( id_organizer )
        REFERENCES organizers ( id_organizer ) ON DELETE CASCADE;

ALTER TABLE room_requests
    ADD CONSTRAINT room_request_location_fk FOREIGN KEY ( id_location )
        REFERENCES locations ( id_location ) ON DELETE CASCADE;

ALTER TABLE room_requests
    ADD CONSTRAINT room_request_organizers_fk FOREIGN KEY ( id_organizer )
        REFERENCES organizers ( id_organizer ) ON DELETE CASCADE;

CREATE OR REPLACE VIEW CITIES_V ( ID_CITY
   , "name"
   , ID_COUNTRY )
 AS SELECT
    ID_CITY
   , "name"
   , ID_COUNTRY
 FROM 
    CITIES 
;

CREATE OR REPLACE VIEW COUNTRIES_V ( ID_COUNTRY
   , "name" )
 AS SELECT
    ID_COUNTRY
   , "name"
 FROM 
    COUNTRIES 
;

CREATE OR REPLACE VIEW CREDENTIALS_V ( ID_CREDENTIAL
   , credential_type
   , "data"
   , created_at
   , ID_ORGANIZER )
 AS SELECT
    ID_CREDENTIAL
   , credential_type
   , "data"
   , created_at
   , ID_ORGANIZER
 FROM 
    CREDENTIALS 
;

CREATE VIEW IMAGES_V ( ID_IMAGE
   , "data"
   , file_name
   , file_suffix
   , created_at
   , ID_ORGANIZER
   , ID_LOCATION
   , ID_ROOM )
 AS SELECT
    ID_IMAGE
   , "data"
   , file_name
   , file_suffix
   , created_at
   , ID_ORGANIZER
   , ID_LOCATION
   , ID_ROOM
 FROM 
    IMAGES 
;

CREATE OR REPLACE VIEW LOCATIONS_V ( ID_LOCATION
   , "name"
   , availability_start
   , availability_end
   , ID_CITY
   , ID_ORGANIZER )
 AS SELECT
    ID_LOCATION
   , "name"
   , availability_start
   , availability_end
   , ID_CITY
   , ID_ORGANIZER
 FROM 
    LOCATIONS 
;

CREATE OR REPLACE VIEW NOTIFICATIONS_V ( 
    ID_NOTIFICATION
    , delivered
   , ID_ORGANIZER
   , ID_ROOM_REQUEST
   , ID_NOTIFICATION_TYPE )
 AS SELECT
  ID_NOTIFICATION
    , delivered
   , ID_ORGANIZER
   , ID_ROOM_REQUEST
   , ID_NOTIFICATION_TYPE 
 FROM 
    NOTIFICATIONS
;

CREATE OR REPLACE VIEW ORGANIZERS_V ( ID_ORGANIZER
   , "name"
   , email
   , ID_ROLE
   , ID_ORGANIZER_SUBSTITUTE )
 AS SELECT
    ID_ORGANIZER
   , "name"
   , email
   , ID_ROLE
   , ID_ORGANIZER_SUBSTITUTE
 FROM 
    ORGANIZERS 
;

CREATE OR REPLACE VIEW RESERVATIONS_V ( ID_RESERVATION
   , "start"
   , "end"
   , ID_ROOM
   , ID_ROOM_REQUEST
   , ID_ORGANIZER )
 AS SELECT
    ID_RESERVATION
   , "start"
   , "end"
   , ID_ROOM
   , ID_ROOM_REQUEST
   , ID_ORGANIZER
 FROM 
    RESERVATIONS 
;

CREATE OR REPLACE VIEW ROLES_V ( ID_ROLE
   , "name" )
 AS SELECT
    ID_ROLE
   , "name"
 FROM 
    ROLES 
;

CREATE OR REPLACE VIEW ROOM_REQUESTS_V (
    id_organizer,
    id_location,
    id_room_request,
    min_capacity,
    reservation_start,
    reservation_end,
    reservation_length,
    "type",
    vc_ready,
    podium_size
) AS
SELECT
    rr.id_organizer,
    rr.id_location,
    rr.id_room_request,
    rr.min_capacity,
    rr.reservation_start,
    rr.reservation_end,
    rr.reservation_length,
    rr."type",
    mr.vc_ready,
    pr.podium_size
FROM room_requests rr
JOIN locations   l  ON l.id_location   = rr.id_location
JOIN organizers  o  ON o.id_organizer  = rr.id_organizer
LEFT JOIN meeting_rrequests      mr ON mr.id_room_request = rr.id_room_request
                                    AND rr."type" = 'MEETING_RREQUEST'
LEFT JOIN presentation_rrequests pr ON pr.id_room_request = rr.id_room_request
                                    AND rr."type" = 'PRESENTATION_RREQUEST';

CREATE OR REPLACE VIEW ROOMS_V (
    id_room,
    "name",
    capacity,
    "type",
    id_location,
    availability_start,
    availability_end,
    vc_ready,
    podium_size,
    id_organizer
) AS
SELECT
    r.id_room,
    r."name",
    r.capacity,
    r."type",
    l.id_location,
    l.availability_start,
    l.availability_end,
    mr.vc_ready,
    pr.podium_size,
    r.id_organizer
FROM
    rooms r
    INNER JOIN locations l ON l.id_location = r.id_location
    LEFT JOIN meeting_rooms mr ON mr.id_room = r.id_room
    LEFT JOIN presentation_rooms pr ON pr.id_room = r.id_room
;


CREATE OR REPLACE VIEW USERS_V ( ID_ORGANIZER, email, credential_type, "data", "name" ) AS
SELECT
	o.ID_ORGANIZER,
	o.email,
	c.credential_type,
	c."data",
	r."name"
FROM ORGANIZERS o 
     JOIN CREDENTIALS c ON o.ID_ORGANIZER = c.ID_ORGANIZER
	JOIN ROLES r ON o.ID_ROLE = r.ID_ROLE
ORDER BY c.created_at DESC 
;

CREATE OR REPLACE TRIGGER fkntm_organizers BEFORE
    UPDATE OF id_organizer_substitute ON organizers
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table ORGANIZERS is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_reservations BEFORE
    UPDATE OF id_room_request ON reservations
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table RESERVATIONS is violated');
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_presentation_rooms BEFORE
    INSERT OR UPDATE OF id_room ON presentation_rooms
    FOR EACH ROW
DECLARE
    d VARCHAR2(17);
BEGIN
    SELECT
        a."type"
    INTO d
    FROM
        rooms a
    WHERE
        a.id_room = :new.id_room;

    IF ( d IS NULL OR d <> 'PRESENTATION_ROOM' ) THEN
        raise_application_error(-20223, 'FK PRESENTATION_ROOM_ROOM_FK in Table PRESENTATION_ROOMS violates Arc constraint on Table ROOMS - discriminator column type doesn''t have value ''PRESENTATION_ROOM'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_meeting_rooms BEFORE
    INSERT OR UPDATE OF id_room ON meeting_rooms
    FOR EACH ROW
DECLARE
    d VARCHAR2(17);
BEGIN
    SELECT
        a."type"
    INTO d
    FROM
        rooms a
    WHERE
        a.id_room = :new.id_room;

    IF ( d IS NULL OR d <> 'MEETING_ROOM' ) THEN
        raise_application_error(-20223, 'FK MEETING_ROOM_ROOM_FK in Table MEETING_ROOMS violates Arc constraint on Table ROOMS - discriminator column type doesn''t have value ''MEETING_ROOM'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_2_meeting_rrequests BEFORE
    INSERT OR UPDATE OF id_room_request ON meeting_rrequests
    FOR EACH ROW
DECLARE
    d VARCHAR2(21);
BEGIN
    SELECT
        a."type"
    INTO d
    FROM
        room_requests a
    WHERE
        a.id_room_request = :new.id_room_request;

    IF ( d IS NULL OR d <> 'MEETING_RREQUEST' ) THEN
        raise_application_error(-20223, 'FK MEETING_RREQUEST_ROOM_REQUEST_FK in Table MEETING_RREQUESTS violates Arc constraint on Table ROOM_REQUESTS - discriminator column type doesn''t have value ''MEETING_RREQUEST'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fka_presentation_rrequests BEFORE
    INSERT OR UPDATE OF id_room_request ON presentation_rrequests
    FOR EACH ROW
DECLARE
    d VARCHAR2(21);
BEGIN
    SELECT
        a."type"
    INTO d
    FROM
        room_requests a
    WHERE
        a.id_room_request = :new.id_room_request;

    IF ( d IS NULL OR d <> 'PRESENTATION_RREQUEST' ) THEN
        raise_application_error(-20223, 'FK PRESENTATION_RREQUEST_ROOM_REQUEST_FK in Table PRESENTATION_RREQUESTS violates Arc constraint on Table ROOM_REQUESTS - discriminator column type doesn''t have value ''PRESENTATION_RREQUEST'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE SEQUENCE cities_id_city_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cities_id_city_trg BEFORE
    INSERT ON cities
    FOR EACH ROW
    WHEN ( new.id_city IS NULL )
BEGIN
    :new.id_city := cities_id_city_seq.nextval;
END;
/

CREATE SEQUENCE notification_types_id_notifica START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER notification_types_id_notifica BEFORE
    INSERT ON notification_types
    FOR EACH ROW
    WHEN ( new.id_notification_type IS NULL )
BEGIN
    :new.id_notification_type := notification_types_id_notifica.nextval;
END;
/

CREATE SEQUENCE countries_id_country_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER countries_id_country_trg BEFORE
    INSERT ON countries
    FOR EACH ROW
    WHEN ( new.id_country IS NULL )
BEGIN
    :new.id_country := countries_id_country_seq.nextval;
END;
/

CREATE SEQUENCE credentials_id_credential_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER credentials_id_credential_trg BEFORE
    INSERT ON credentials
    FOR EACH ROW
    WHEN ( new.id_credential IS NULL )
BEGIN
    :new.id_credential := credentials_id_credential_seq.nextval;
END;
/

CREATE SEQUENCE images_id_image_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER images_id_image_trg BEFORE
    INSERT ON images
    FOR EACH ROW
    WHEN ( new.id_image IS NULL )
BEGIN
    :new.id_image := images_id_image_seq.nextval;
END;
/

CREATE SEQUENCE locations_id_location_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER locations_id_location_trg BEFORE
    INSERT ON locations
    FOR EACH ROW
    WHEN ( new.id_location IS NULL )
BEGIN
    :new.id_location := locations_id_location_seq.nextval;
END;
/

CREATE SEQUENCE notifications_id_notification START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER notifications_id_notification BEFORE
    INSERT ON notifications
    FOR EACH ROW
    WHEN ( new.id_notification IS NULL )
BEGIN
    :new.id_notification := notifications_id_notification.nextval;
END;
/

CREATE SEQUENCE organizers_id_organizer_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER organizers_id_organizer_trg BEFORE
    INSERT ON organizers
    FOR EACH ROW
    WHEN ( new.id_organizer IS NULL )
BEGIN
    :new.id_organizer := organizers_id_organizer_seq.nextval;
END;
/

CREATE SEQUENCE reservations_id_reservation START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER reservations_id_reservation BEFORE
    INSERT ON reservations
    FOR EACH ROW
    WHEN ( new.id_reservation IS NULL )
BEGIN
    :new.id_reservation := reservations_id_reservation.nextval;
END;
/

CREATE SEQUENCE roles_id_role_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER roles_id_role_trg BEFORE
    INSERT ON roles
    FOR EACH ROW
    WHEN ( new.id_role IS NULL )
BEGIN
    :new.id_role := roles_id_role_seq.nextval;
END;
/

CREATE SEQUENCE room_requests_id_room_request START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER room_requests_id_room_request BEFORE
    INSERT ON room_requests
    FOR EACH ROW
    WHEN ( new.id_room_request IS NULL )
BEGIN
    :new.id_room_request := room_requests_id_room_request.nextval;
END;
/

CREATE SEQUENCE rooms_id_room_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rooms_id_room_trg BEFORE
    INSERT ON rooms
    FOR EACH ROW
    WHEN ( new.id_room IS NULL )
BEGIN
    :new.id_room := rooms_id_room_seq.nextval;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             6
-- ALTER TABLE                             43
-- CREATE VIEW                             12
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          17
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         11
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0



-- Automatická alokace pro meeting požadavky
CREATE OR REPLACE TRIGGER trg_meeting_rreq_auto_alloc
AFTER INSERT ON meeting_rrequests
FOR EACH ROW
BEGIN
    reservations_pkg.process_request(
        p_id_room_request => :NEW.id_room_request,
        p_type            => 'MEETING_RREQUEST',
        p_vc_ready        => :NEW.vc_ready,
        p_podium_size     => NULL
    );
END;
/

-- Automatická alokace pro presentation požadavky
CREATE OR REPLACE TRIGGER trg_presentation_rreq_auto_alloc
AFTER INSERT ON presentation_rrequests
FOR EACH ROW
BEGIN
    reservations_pkg.process_request(
        p_id_room_request => :NEW.id_room_request,
        p_type            => 'PRESENTATION_RREQUEST',
        p_vc_ready        => NULL,
        p_podium_size     => :NEW.podium_size
    );
END;
/

CREATE OR REPLACE VIEW organizers_hierarchy_v AS
SELECT 
    LEVEL as hierarchy_level,
    id_organizer,
    "name",
    email,
    id_organizer_substitute,
    SYS_CONNECT_BY_PATH("name", ' → ') as hierarchy_path,
    CONNECT_BY_ROOT "name" as top_organizer
FROM organizers
START WITH id_organizer_substitute IS NULL
CONNECT BY PRIOR id_organizer = id_organizer_substitute
ORDER SIBLINGS BY "name";

-- Tabulka pro audit log
CREATE TABLE audit_log (
    id_log NUMBER PRIMARY KEY,
    table_name VARCHAR2(30) NOT NULL,
    operation VARCHAR2(10) NOT NULL,
    record_id NUMBER,
    id_organizer NUMBER,
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    old_values VARCHAR2(1000),
    new_values VARCHAR2(1000)
);

CREATE SEQUENCE audit_log_seq START WITH 1 NOCACHE ORDER;

-- Audit trigger pro tabulku RESERVATIONS
CREATE OR REPLACE TRIGGER trg_audit_reservations
AFTER INSERT OR UPDATE OR DELETE ON reservations
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
    v_organizer_id NUMBER;
BEGIN
    -- Určení typu operace
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_organizer_id := :NEW.id_organizer;
        v_new_values := 'Room:' || :NEW.id_room || 
                       ',Start:' || TO_CHAR(:NEW."start", 'DD.MM.YYYY HH24:MI') ||
                       ',End:' || TO_CHAR(:NEW."end", 'DD.MM.YYYY HH24:MI');
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_organizer_id := :NEW.id_organizer;
        v_old_values := 'Room:' || :OLD.id_room || 
                       ',Start:' || TO_CHAR(:OLD."start", 'DD.MM.YYYY HH24:MI');
        v_new_values := 'Room:' || :NEW.id_room || 
                       ',Start:' || TO_CHAR(:NEW."start", 'DD.MM.YYYY HH24:MI');
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_organizer_id := :OLD.id_organizer;
        v_old_values := 'Room:' || :OLD.id_room || 
                       ',Start:' || TO_CHAR(:OLD."start", 'DD.MM.YYYY HH24:MI') ||
                       ',End:' || TO_CHAR(:OLD."end", 'DD.MM.YYYY HH24:MI');
    END IF;
    
    -- Vložení do audit logu
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'RESERVATIONS',
        v_operation,
        COALESCE(:NEW.id_reservation, :OLD.id_reservation),
        v_organizer_id,
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku ROOMS
CREATE OR REPLACE TRIGGER trg_audit_rooms
AFTER INSERT OR UPDATE OR DELETE ON rooms
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Name:' || :NEW."name" || ',Capacity:' || :NEW.capacity || ',Type:' || :NEW."type";
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Name:' || :OLD."name" || ',Capacity:' || :OLD.capacity;
        v_new_values := 'Name:' || :NEW."name" || ',Capacity:' || :NEW.capacity;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Name:' || :OLD."name" || ',Capacity:' || :OLD.capacity || ',Type:' || :OLD."type";
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'ROOMS',
        v_operation,
        COALESCE(:NEW.id_room, :OLD.id_room),
        COALESCE(:NEW.id_organizer, :OLD.id_organizer),
        v_old_values,
        v_new_values
    );
END;
/

ALTER TABLE room_requests MODIFY reservation_length INTERVAL DAY(3) TO SECOND(0);

CREATE OR REPLACE VIEW IMAGES_WITH_DETAIL_V (
    ID_IMAGE
   , "data"
   , file_name
   , file_suffix
   , created_at
   , ID_ORGANIZER
   , organizer_name
   , ID_LOCATION
   , location_name
   , ID_ROOM
   , room_name
   , id_city
   , city_name
) AS
SELECT 
    i.ID_IMAGE,
    i."data",
    i.file_name,
    i.file_suffix,
    i.created_at,
    i.ID_ORGANIZER,
    o."name" as organizer_name,
    i.ID_LOCATION,
    l."name" as location_name,
    i.ID_ROOM,
    r."name" as room_name,
    c.id_city,
    c."name" as city_name
FROM IMAGES i
INNER JOIN rooms r ON i.id_room = r.id_room
INNER JOIN locations l ON i.id_location = l.id_location
INNER JOIN cities c ON l.id_city = c.id_city
INNER JOIN organizers o ON i.id_organizer = o.id_organizer;


-- Audit trigger pro tabulku ORGANIZERS
CREATE OR REPLACE TRIGGER trg_audit_organizers
AFTER INSERT OR UPDATE OR DELETE ON organizers
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Name:' || :NEW."name" || 
                       ',Email:' || :NEW.email ||
                       ',Role:' || :NEW.id_role;
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Name:' || :OLD."name" || 
                       ',Email:' || :OLD.email ||
                       ',Role:' || :OLD.id_role;
        v_new_values := 'Name:' || :NEW."name" || 
                       ',Email:' || :NEW.email ||
                       ',Role:' || :NEW.id_role;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Name:' || :OLD."name" || 
                       ',Email:' || :OLD.email ||
                       ',Role:' || :OLD.id_role;
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'ORGANIZERS',
        v_operation,
        COALESCE(:NEW.id_organizer, :OLD.id_organizer),
        COALESCE(:NEW.id_organizer, :OLD.id_organizer),
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku LOCATIONS
CREATE OR REPLACE TRIGGER trg_audit_locations
AFTER INSERT OR UPDATE OR DELETE ON locations
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Name:' || :NEW."name" || 
                       ',City:' || :NEW.id_city ||
                       ',Start:' || TO_CHAR(:NEW.availability_start, 'DD.MM.YYYY') ||
                       ',End:' || TO_CHAR(:NEW.availability_end, 'DD.MM.YYYY');
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Name:' || :OLD."name" || 
                       ',City:' || :OLD.id_city ||
                       ',Start:' || TO_CHAR(:OLD.availability_start, 'DD.MM.YYYY');
        v_new_values := 'Name:' || :NEW."name" || 
                       ',City:' || :NEW.id_city ||
                       ',Start:' || TO_CHAR(:NEW.availability_start, 'DD.MM.YYYY');
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Name:' || :OLD."name" || 
                       ',City:' || :OLD.id_city ||
                       ',Start:' || TO_CHAR(:OLD.availability_start, 'DD.MM.YYYY') ||
                       ',End:' || TO_CHAR(:OLD.availability_end, 'DD.MM.YYYY');
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'LOCATIONS',
        v_operation,
        COALESCE(:NEW.id_location, :OLD.id_location),
        COALESCE(:NEW.id_organizer, :OLD.id_organizer),
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku ROOM_REQUESTS
CREATE OR REPLACE TRIGGER trg_audit_room_requests
AFTER INSERT OR UPDATE OR DELETE ON room_requests
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Type:' || :NEW."type" || 
                       ',MinCap:' || :NEW.min_capacity ||
                       ',Start:' || TO_CHAR(:NEW.reservation_start, 'DD.MM.YYYY HH24:MI') ||
                       ',Location:' || :NEW.id_location;
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Type:' || :OLD."type" || 
                       ',MinCap:' || :OLD.min_capacity ||
                       ',Start:' || TO_CHAR(:OLD.reservation_start, 'DD.MM.YYYY HH24:MI');
        v_new_values := 'Type:' || :NEW."type" || 
                       ',MinCap:' || :NEW.min_capacity ||
                       ',Start:' || TO_CHAR(:NEW.reservation_start, 'DD.MM.YYYY HH24:MI');
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Type:' || :OLD."type" || 
                       ',MinCap:' || :OLD.min_capacity ||
                       ',Start:' || TO_CHAR(:OLD.reservation_start, 'DD.MM.YYYY HH24:MI') ||
                       ',Location:' || :OLD.id_location;
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'ROOM_REQUESTS',
        v_operation,
        COALESCE(:NEW.id_room_request, :OLD.id_room_request),
        COALESCE(:NEW.id_organizer, :OLD.id_organizer),
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku CREDENTIALS
CREATE OR REPLACE TRIGGER trg_audit_credentials
AFTER INSERT OR UPDATE OR DELETE ON credentials
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Type:' || :NEW.credential_type || 
                       ',Created:' || TO_CHAR(:NEW.created_at, 'DD.MM.YYYY HH24:MI:SS');
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Type:' || :OLD.credential_type || 
                       ',Created:' || TO_CHAR(:OLD.created_at, 'DD.MM.YYYY HH24:MI:SS');
        v_new_values := 'Type:' || :NEW.credential_type || 
                       ',Created:' || TO_CHAR(:NEW.created_at, 'DD.MM.YYYY HH24:MI:SS');
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Type:' || :OLD.credential_type || 
                       ',Created:' || TO_CHAR(:OLD.created_at, 'DD.MM.YYYY HH24:MI:SS');
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'CREDENTIALS',
        v_operation,
        COALESCE(:NEW.id_credential, :OLD.id_credential),
        COALESCE(:NEW.id_organizer, :OLD.id_organizer),
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku NOTIFICATIONS
CREATE OR REPLACE TRIGGER trg_audit_notifications
AFTER INSERT OR UPDATE OR DELETE ON notifications
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Delivered:' || :NEW.delivered || 
                       ',Type:' || :NEW.id_notification_type ||
                       ',Request:' || :NEW.id_room_request;
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Delivered:' || :OLD.delivered || 
                       ',Type:' || :OLD.id_notification_type;
        v_new_values := 'Delivered:' || :NEW.delivered || 
                       ',Type:' || :NEW.id_notification_type;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Delivered:' || :OLD.delivered || 
                       ',Type:' || :OLD.id_notification_type ||
                       ',Request:' || :OLD.id_room_request;
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'NOTIFICATIONS',
        v_operation,
        COALESCE(:NEW.id_notification, :OLD.id_notification),
        COALESCE(:NEW.id_organizer, :OLD.id_organizer),
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku IMAGES
CREATE OR REPLACE TRIGGER trg_audit_images
AFTER INSERT OR UPDATE OR DELETE ON images
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'File:' || :NEW.file_name || '.' || :NEW.file_suffix || 
                       ',Room:' || :NEW.id_room ||
                       ',Location:' || :NEW.id_location ||
                       ',Created:' || TO_CHAR(:NEW.created_at, 'DD.MM.YYYY');
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'File:' || :OLD.file_name || '.' || :OLD.file_suffix || 
                       ',Room:' || :OLD.id_room;
        v_new_values := 'File:' || :NEW.file_name || '.' || :NEW.file_suffix || 
                       ',Room:' || :NEW.id_room;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'File:' || :OLD.file_name || '.' || :OLD.file_suffix || 
                       ',Room:' || :OLD.id_room ||
                       ',Location:' || :OLD.id_location ||
                       ',Created:' || TO_CHAR(:OLD.created_at, 'DD.MM.YYYY');
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'IMAGES',
        v_operation,
        COALESCE(:NEW.id_image, :OLD.id_image),
        COALESCE(:NEW.id_organizer, :OLD.id_organizer),
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku ROLES
CREATE OR REPLACE TRIGGER trg_audit_roles
AFTER INSERT OR UPDATE OR DELETE ON roles
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Name:' || :NEW."name";
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Name:' || :OLD."name";
        v_new_values := 'Name:' || :NEW."name";
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Name:' || :OLD."name";
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'ROLES',
        v_operation,
        COALESCE(:NEW.id_role, :OLD.id_role),
        NULL,
        v_old_values,
        v_new_values
    );
END;
/

-- Oprava audit triggeru pro MEETING_ROOMS
CREATE OR REPLACE TRIGGER trg_audit_meeting_rooms
AFTER INSERT OR UPDATE OR DELETE ON meeting_rooms
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
    v_organizer_id NUMBER;
BEGIN
    -- Získání id_organizer
    BEGIN
        IF INSERTING OR UPDATING THEN
            SELECT id_organizer INTO v_organizer_id 
            FROM rooms WHERE id_room = :NEW.id_room;
        ELSE
            SELECT id_organizer INTO v_organizer_id 
            FROM rooms WHERE id_room = :OLD.id_room;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_organizer_id := NULL;
    END;
    
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'VCReady:' || :NEW.vc_ready;
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'VCReady:' || :OLD.vc_ready;
        v_new_values := 'VCReady:' || :NEW.vc_ready;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'VCReady:' || :OLD.vc_ready;
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'MEETING_ROOMS',
        v_operation,
        COALESCE(:NEW.id_room, :OLD.id_room),
        v_organizer_id,
        v_old_values,
        v_new_values
    );
    

    
EXCEPTION
    WHEN OTHERS THEN
        --zalogujte chybu, necommitujte
        DBMS_OUTPUT.PUT_LINE('Audit error: ' || SQLERRM);
        -- Nechte hlavní transakci rozhodnout o rollbacku
END;
/

-- Oprava audit triggeru pro PRESENTATION_ROOMS
CREATE OR REPLACE TRIGGER trg_audit_presentation_rooms
AFTER INSERT OR UPDATE OR DELETE ON presentation_rooms
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
    v_organizer_id NUMBER;
BEGIN
    BEGIN
        IF INSERTING OR UPDATING THEN
            SELECT id_organizer INTO v_organizer_id 
            FROM rooms WHERE id_room = :NEW.id_room;
        ELSE
            SELECT id_organizer INTO v_organizer_id 
            FROM rooms WHERE id_room = :OLD.id_room;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_organizer_id := NULL;
    END;
    
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'PodiumSize:' || :NEW.podium_size;
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'PodiumSize:' || :OLD.podium_size;
        v_new_values := 'PodiumSize:' || :NEW.podium_size;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'PodiumSize:' || :OLD.podium_size;
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'PRESENTATION_ROOMS',
        v_operation,
        COALESCE(:NEW.id_room, :OLD.id_room),
        v_organizer_id,
        v_old_values,
        v_new_values
    );
END;
/

DROP TRIGGER trg_audit_presentation_rrequests;

-- OPRAVA: Audit trigger pro MEETING_RREQUESTS s detekcí MERGE
CREATE OR REPLACE TRIGGER trg_audit_meeting_rrequests
AFTER INSERT OR UPDATE OR DELETE ON meeting_rrequests
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
    v_organizer_id NUMBER;
BEGIN
    -- Získání id_organizer z hlavní tabulky room_requests
    BEGIN
        IF INSERTING OR UPDATING THEN
            SELECT id_organizer INTO v_organizer_id 
            FROM room_requests WHERE id_room_request = :NEW.id_room_request;
        ELSE
            SELECT id_organizer INTO v_organizer_id 
            FROM room_requests WHERE id_room_request = :OLD.id_room_request;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_organizer_id := NULL;
    END;
    
    -- KLÍČOVÁ OPRAVA: Rozlišení mezi INSERT a UPDATE při MERGE
    IF INSERTING THEN
        -- Kontrola, zda záznam již existoval (znamená UPDATE přes MERGE)
        IF :OLD.id_room_request IS NOT NULL THEN
            -- Toto je UPDATE přes MERGE, nikoliv INSERT
            v_operation := 'UPDATE';
            v_old_values := 'VCReady:' || :OLD.vc_ready;
            v_new_values := 'VCReady:' || :NEW.vc_ready;
        ELSE
            -- Toto je skutečný INSERT
            v_operation := 'INSERT';
            v_new_values := 'VCReady:' || :NEW.vc_ready;
        END IF;
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'VCReady:' || :OLD.vc_ready;
        v_new_values := 'VCReady:' || :NEW.vc_ready;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'VCReady:' || :OLD.vc_ready;
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'MEETING_RREQUESTS',
        v_operation,
        COALESCE(:NEW.id_room_request, :OLD.id_room_request),
        v_organizer_id,
        v_old_values,
        v_new_values
    );
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; -- Rollback pouze audit logu, ne hlavní transakce
        -- Nechceme přerušit hlavní transakci kvůli chybě v auditu
END;
/

-- OPRAVA: Audit trigger pro PRESENTATION_RREQUESTS s detekcí MERGE
CREATE OR REPLACE TRIGGER trg_audit_presentation_rrequests
AFTER INSERT OR UPDATE OR DELETE ON presentation_rrequests
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
    v_organizer_id NUMBER;
BEGIN
    -- Získání id_organizer z hlavní tabulky room_requests
    BEGIN
        IF INSERTING OR UPDATING THEN
            SELECT id_organizer INTO v_organizer_id 
            FROM room_requests WHERE id_room_request = :NEW.id_room_request;
        ELSE
            SELECT id_organizer INTO v_organizer_id 
            FROM room_requests WHERE id_room_request = :OLD.id_room_request;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_organizer_id := NULL;
    END;
    
    -- KLÍČOVÁ OPRAVA: Rozlišení mezi INSERT a UPDATE při MERGE
    IF INSERTING THEN
        -- Kontrola, zda záznam již existoval (znamená UPDATE přes MERGE)
        IF :OLD.id_room_request IS NOT NULL THEN
            -- Toto je UPDATE přes MERGE, nikoliv INSERT
            v_operation := 'UPDATE';
            v_old_values := 'PodiumSize:' || :OLD.podium_size;
            v_new_values := 'PodiumSize:' || :NEW.podium_size;
        ELSE
            -- Toto je skutečný INSERT
            v_operation := 'INSERT';
            v_new_values := 'PodiumSize:' || :NEW.podium_size;
        END IF;
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'PodiumSize:' || :OLD.podium_size;
        v_new_values := 'PodiumSize:' || :NEW.podium_size;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'PodiumSize:' || :OLD.podium_size;
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'PRESENTATION_RREQUESTS',
        v_operation,
        COALESCE(:NEW.id_room_request, :OLD.id_room_request),
        v_organizer_id,
        v_old_values,
        v_new_values
    );
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;
/

-- Audit trigger pro tabulku CITIES
CREATE OR REPLACE TRIGGER trg_audit_cities
AFTER INSERT OR UPDATE OR DELETE ON cities
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Name:' || :NEW."name" || 
                       ',Country:' || :NEW.id_country;
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Name:' || :OLD."name" || 
                       ',Country:' || :OLD.id_country;
        v_new_values := 'Name:' || :NEW."name" || 
                       ',Country:' || :NEW.id_country;
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Name:' || :OLD."name" || 
                       ',Country:' || :OLD.id_country;
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'CITIES',
        v_operation,
        COALESCE(:NEW.id_city, :OLD.id_city),
        NULL,  -- Cities nemají vztah k organizátorům
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku COUNTRIES
CREATE OR REPLACE TRIGGER trg_audit_countries
AFTER INSERT OR UPDATE OR DELETE ON countries
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Name:' || :NEW."name";
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Name:' || :OLD."name";
        v_new_values := 'Name:' || :NEW."name";
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Name:' || :OLD."name";
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'COUNTRIES',
        v_operation,
        COALESCE(:NEW.id_country, :OLD.id_country),
        NULL,  -- Countries nemají vztah k organizátorům
        v_old_values,
        v_new_values
    );
END;
/

-- Audit trigger pro tabulku NOTIFICATION_TYPES
CREATE OR REPLACE TRIGGER trg_audit_notification_types
AFTER INSERT OR UPDATE OR DELETE ON notification_types
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
    v_old_values VARCHAR2(1000);
    v_new_values VARCHAR2(1000);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        v_new_values := 'Code:' || :NEW."code" || 
                       ',Name:' || :NEW."name" ||
                       ',Desc:' || :NEW."description";
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_old_values := 'Code:' || :OLD."code" || 
                       ',Name:' || :OLD."name";
        v_new_values := 'Code:' || :NEW."code" || 
                       ',Name:' || :NEW."name";
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        v_old_values := 'Code:' || :OLD."code" || 
                       ',Name:' || :OLD."name" ||
                       ',Desc:' || :OLD."description";
    END IF;
    
    INSERT INTO audit_log (
        id_log, table_name, operation, record_id, id_organizer, 
        old_values, new_values
    ) VALUES (
        audit_log_seq.NEXTVAL,
        'NOTIFICATION_TYPES',
        v_operation,
        COALESCE(:NEW.id_notification_type, :OLD.id_notification_type),
        NULL,  -- Notification types nemají vztah k organizátorům
        v_old_values,
        v_new_values
    );
END;
/

CREATE OR REPLACE TRIGGER trg_reservation_delete_realloc
FOR DELETE ON reservations
COMPOUND TRIGGER

    TYPE t_deleted_reservations IS TABLE OF reservations%ROWTYPE INDEX BY PLS_INTEGER;
    g_deleted_reservations t_deleted_reservations;
    g_index PLS_INTEGER := 0;

    AFTER EACH ROW IS
    BEGIN
        --KONTROLA: Pokud probíhá cancel, NEUKLÁDÁME (ale nepřerušujeme)
        IF NOT locations_pkg.g_cancel_in_progress THEN
            g_index := g_index + 1;
            g_deleted_reservations(g_index).id_reservation := :OLD.id_reservation;
            g_deleted_reservations(g_index).id_room := :OLD.id_room;
            g_deleted_reservations(g_index).id_room_request := :OLD.id_room_request;
            
            DBMS_OUTPUT.PUT_LINE('Uložena rezervace: ' || :OLD.id_reservation);
        ELSE
            DBMS_OUTPUT.PUT_LINE('Trigger pozastaven (cancel probíhá)');
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        v_id_location locations.id_location%TYPE;
        v_processed_locations SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST();
        v_location_exists BOOLEAN;
    BEGIN
        --KONTROLA: Pokud probíhá cancel NEBO není co zpracovat, UKONČÍME
        IF locations_pkg.g_cancel_in_progress THEN
            DBMS_OUTPUT.PUT_LINE('Realokace přeskočena (cancel probíhá)');
            g_deleted_reservations.DELETE;
            g_index := 0;
            -- Žádný RETURN, jen necháme proceduru skončit
        ELSIF g_deleted_reservations.COUNT = 0 THEN
            DBMS_OUTPUT.PUT_LINE('Žádné rezervace ke zpracování');
            -- Žádný RETURN, jen necháme proceduru skončit
        ELSE
            --NORMÁLNÍ ZPRACOVÁNÍ
            DBMS_OUTPUT.PUT_LINE('=== SPUŠTĚNA REALOKACE (' || g_deleted_reservations.COUNT || ' rezervací) ===');
            
            FOR i IN 1..g_deleted_reservations.COUNT LOOP
                BEGIN
                    SELECT r.id_location INTO v_id_location
                    FROM rooms r
                    WHERE r.id_room = g_deleted_reservations(i).id_room;
                    
                    DELETE FROM room_requests
                    WHERE id_room_request = g_deleted_reservations(i).id_room_request;
                    
                    DBMS_OUTPUT.PUT_LINE('Smazán request: ' || g_deleted_reservations(i).id_room_request);
                    
                    -- Realokace pouze jednou pro každou lokaci
                    v_location_exists := FALSE;
                    FOR j IN 1..v_processed_locations.COUNT LOOP
                        IF v_processed_locations(j) = v_id_location THEN
                            v_location_exists := TRUE;
                            EXIT;
                        END IF;
                    END LOOP;
                    
                    IF NOT v_location_exists THEN
                        v_processed_locations.EXTEND;
                        v_processed_locations(v_processed_locations.COUNT) := v_id_location;
                        
                        DBMS_OUTPUT.PUT_LINE('Realokace lokace: ' || v_id_location);
                        reservations_pkg.batch_process_location_requests(p_id_location => v_id_location);
                    END IF;
                    
                EXCEPTION
                    WHEN NO_DATA_FOUND THEN
                        DBMS_OUTPUT.PUT_LINE('Místnost nenalezena');
                        DELETE FROM room_requests
                        WHERE id_room_request = g_deleted_reservations(i).id_room_request;
                    WHEN OTHERS THEN
                        DBMS_OUTPUT.PUT_LINE('Chyba: ' || SQLERRM);
                END;
            END LOOP;
            
            DBMS_OUTPUT.PUT_LINE('=== REALOKACE DOKONČENA ===');
        END IF;
        
        -- Vždy vyčistíme kolekci na konci
        g_deleted_reservations.DELETE;
        g_index := 0;
        
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('KRITICKÁ CHYBA v realokaci: ' || SQLERRM);
            g_deleted_reservations.DELETE;
            g_index := 0;
            RAISE;
    END AFTER STATEMENT;

END trg_reservation_delete_realloc;


-- =====================================================
-- NOVÉ POHLEDY PRO ODSTRANĚNÍ CYKLICKÝCH DOTAZŮ
-- =====================================================

-- ✅ 1. POHLED PRO ROOM_REQUESTS S PLNÝMI DETAILY
-- Nahrazuje opakované volání Location.GetLocation() a Organiser.GetOrganiser()
CREATE OR REPLACE VIEW ROOM_REQUESTS_WITH_DETAILS_V AS
SELECT 
    -- Room Request údaje
    rr.id_room_request,
    rr.min_capacity,
    rr.reservation_start,
    rr.reservation_end,
    rr.reservation_length,
    rr."type",
    mr.vc_ready,
    pr.podium_size,
    
    -- Location údaje
    l.id_location,
    l."name" AS location_name,
    l.availability_start,
    l.availability_end,
    
    -- City údaje
    c.id_city,
    c."name" AS city_name,
    
    -- Country údaje
    co.id_country,
    co."name" AS country_name,
    
    -- Organizer údaje
    o.id_organizer,
    o."name" AS organizer_name,
    o.email AS organizer_email,
    
    -- Organizer Role údaje
    r.id_role,
    r."name" AS role_name
    
FROM room_requests rr
INNER JOIN locations l ON rr.id_location = l.id_location
INNER JOIN cities c ON l.id_city = c.id_city
INNER JOIN countries co ON c.id_country = co.id_country
INNER JOIN organizers o ON rr.id_organizer = o.id_organizer
INNER JOIN roles r ON o.id_role = r.id_role
LEFT JOIN meeting_rrequests mr ON mr.id_room_request = rr.id_room_request
    AND rr."type" = 'MEETING_RREQUEST'
LEFT JOIN presentation_rrequests pr ON pr.id_room_request = rr.id_room_request
    AND rr."type" = 'PRESENTATION_RREQUEST';

-- ✅ 2. POHLED PRO ORGANIZERS S PLNÝMI DETAILY (včetně role a náhradníka)
CREATE OR REPLACE VIEW ORGANIZERS_WITH_DETAILS_V AS
SELECT 
    o.id_organizer,
    o."name",
    o.email,
    o.id_organizer_substitute,
    
    -- Role údaje
    r.id_role,
    r."name" AS role_name,
    
    -- Substitute údaje (pokud existuje)
    s.id_organizer AS substitute_id,
    s."name" AS substitute_name,
    s.email AS substitute_email,
    
    -- Substitute Role údaje
    sr.id_role AS substitute_role_id,
    sr."name" AS substitute_role_name
    
FROM organizers o
INNER JOIN roles r ON o.id_role = r.id_role
LEFT JOIN organizers s ON o.id_organizer_substitute = s.id_organizer
LEFT JOIN roles sr ON s.id_role = sr.id_role;

-- ✅ 3. POHLED PRO CITIES S COUNTRY DETAILY
CREATE OR REPLACE VIEW CITIES_WITH_COUNTRY_V AS
SELECT 
    c.id_city,
    c."name" AS city_name,
    
    -- Country údaje
    co.id_country,
    co."name" AS country_name
    
FROM cities c
INNER JOIN countries co ON c.id_country = co.id_country;

COMMIT;