-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-11-07 15:13:48 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cities (
    id_city            NUMBER NOT NULL,
    name               VARCHAR2(64) NOT NULL,
    country_id_country NUMBER NOT NULL
);

ALTER TABLE cities ADD CONSTRAINT city_pk PRIMARY KEY ( id_city );

ALTER TABLE cities ADD CONSTRAINT city_name_id_country_un UNIQUE ( name,
                                                                   country_id_country );

CREATE TABLE countries (
    id_country NUMBER NOT NULL,
    name       VARCHAR2(32) NOT NULL
);

ALTER TABLE countries ADD CONSTRAINT country_pk PRIMARY KEY ( id_country );

ALTER TABLE countries ADD CONSTRAINT country_name_un UNIQUE ( name );

CREATE TABLE credentials (
    id_credential          INTEGER NOT NULL,
    credential_type        CHAR(8) NOT NULL,
    data                   VARCHAR2(256) NOT NULL,
    organizer_id_organizer NUMBER NOT NULL,
    created_at             TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
);

ALTER TABLE credentials ADD CONSTRAINT credential_pk PRIMARY KEY ( id_credential );

CREATE TABLE locations (
    id_location            NUMBER NOT NULL,
    name                   VARCHAR2(32) NOT NULL,
    availabilitystart      DATE NOT NULL,
    availabilityend        DATE NOT NULL,
    city_id_city           NUMBER NOT NULL,
    organizer_id_organizer NUMBER NOT NULL
);

ALTER TABLE locations ADD CONSTRAINT location_pk PRIMARY KEY ( id_location );

ALTER TABLE locations ADD CONSTRAINT location_name_id_city_un UNIQUE ( name,
                                                                       city_id_city );

CREATE TABLE meeting_rooms (
    id_room NUMBER NOT NULL,
    vcready CHAR(1) NOT NULL
);

ALTER TABLE meeting_rooms ADD CONSTRAINT meeting_room_pk PRIMARY KEY ( id_room );

CREATE TABLE meeting_rrequests (
    id_room_request NUMBER NOT NULL,
    vcready         CHAR(1)
);

ALTER TABLE meeting_rrequests ADD CONSTRAINT meeting_rrequest_pk PRIMARY KEY ( id_room_request );

CREATE TABLE notifications (
    id_notification              INTEGER NOT NULL,
    notification_type            VARCHAR2(16) NOT NULL,
    delivered                    CHAR(1) NOT NULL,
    organizer_id_organizer       NUMBER NOT NULL,
    room_request_id_room_request NUMBER NOT NULL
);

CREATE UNIQUE INDEX notification__idx ON
    notifications (
        room_request_id_room_request
    ASC );

ALTER TABLE notifications ADD CONSTRAINT notification_pk PRIMARY KEY ( id_notification );

CREATE TABLE organizers (
    id_organizer NUMBER NOT NULL,
    name         VARCHAR2(64) NOT NULL,
    email        VARCHAR2(320) NOT NULL,
    priority     NUMBER DEFAULT 1000 NOT NULL,
    role_id_role INTEGER
);

ALTER TABLE organizers ADD CONSTRAINT organizer_pk PRIMARY KEY ( id_organizer );

CREATE TABLE presentation_rooms (
    id_room    NUMBER NOT NULL,
    podiumsize NUMBER NOT NULL
);

ALTER TABLE presentation_rooms ADD CONSTRAINT presentation_room_pk PRIMARY KEY ( id_room );

CREATE TABLE presentation_rrequests (
    id_room_request NUMBER NOT NULL,
    podiumsize      NUMBER
);

ALTER TABLE presentation_rrequests ADD CONSTRAINT presentation_rrequest_pk PRIMARY KEY ( id_room_request );

CREATE TABLE reservations (
    id_reservation               NUMBER NOT NULL,
    "start"                      DATE NOT NULL,
    end                          DATE NOT NULL,
    room_id_room                 NUMBER NOT NULL,
    room_request_id_room_request NUMBER NOT NULL,
    organizer_id_organizer       NUMBER NOT NULL
);

CREATE UNIQUE INDEX reservation__idx ON
    reservations (
        room_request_id_room_request
    ASC );

ALTER TABLE reservations ADD CONSTRAINT reservation_pk PRIMARY KEY ( id_reservation );

CREATE TABLE roles (
    id_role INTEGER NOT NULL,
    name    VARCHAR2(32) NOT NULL
);

ALTER TABLE roles ADD CONSTRAINT role_pk PRIMARY KEY ( id_role );

CREATE TABLE room_requests (
    id_room_request        NUMBER NOT NULL,
    mincapacity            NUMBER NOT NULL,
    type                   VARCHAR2(21) NOT NULL,
    reservationstart       DATE NOT NULL,
    reservationend         DATE,
    reservationlength      DATE,
    location_id_location   NUMBER,
    organizer_id_organizer NUMBER NOT NULL
);

ALTER TABLE room_requests
    ADD CONSTRAINT ch_inh_room_request CHECK ( type IN ( 'MEETING_RREQUEST', 'PRESENTATION_RREQUEST', 'ROOM_REQUEST' ) );

ALTER TABLE room_requests ADD CONSTRAINT room_request_pk PRIMARY KEY ( id_room_request );

CREATE TABLE rooms (
    id_room                NUMBER NOT NULL,
    name                   VARCHAR2(32) NOT NULL,
    capacity               NUMBER NOT NULL,
    type                   VARCHAR2(17) NOT NULL,
    location_id_location   NUMBER NOT NULL,
    organizer_id_organizer NUMBER NOT NULL
);

ALTER TABLE rooms
    ADD CONSTRAINT ch_inh_room CHECK ( type IN ( 'MEETING_ROOM', 'PRESENTATION_ROOM', 'ROOM' ) );

ALTER TABLE rooms ADD CONSTRAINT room_pk PRIMARY KEY ( id_room );

ALTER TABLE rooms ADD CONSTRAINT room_name_un UNIQUE ( name );

ALTER TABLE cities
    ADD CONSTRAINT city_country_fk FOREIGN KEY ( country_id_country )
        REFERENCES countries ( id_country );

ALTER TABLE credentials
    ADD CONSTRAINT credential_organizer_fk FOREIGN KEY ( organizer_id_organizer )
        REFERENCES organizers ( id_organizer );

ALTER TABLE locations
    ADD CONSTRAINT location_city_fk FOREIGN KEY ( city_id_city )
        REFERENCES cities ( id_city );

ALTER TABLE locations
    ADD CONSTRAINT location_organizer_fk FOREIGN KEY ( organizer_id_organizer )
        REFERENCES organizers ( id_organizer );

ALTER TABLE meeting_rooms
    ADD CONSTRAINT meeting_room_room_fk FOREIGN KEY ( id_room )
        REFERENCES rooms ( id_room );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE meeting_rrequests
    ADD CONSTRAINT meeting_rrequest_room_request_fk FOREIGN KEY ( id_room_request )
        REFERENCES room_requests ( id_room_request );

ALTER TABLE notifications
    ADD CONSTRAINT notification_organizer_fk FOREIGN KEY ( organizer_id_organizer )
        REFERENCES organizers ( id_organizer );

ALTER TABLE notifications
    ADD CONSTRAINT notification_room_request_fk FOREIGN KEY ( room_request_id_room_request )
        REFERENCES room_requests ( id_room_request );

ALTER TABLE organizers
    ADD CONSTRAINT organizer_role_fk FOREIGN KEY ( role_id_role )
        REFERENCES roles ( id_role );

ALTER TABLE presentation_rooms
    ADD CONSTRAINT presentation_room_room_fk FOREIGN KEY ( id_room )
        REFERENCES rooms ( id_room );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE presentation_rrequests
    ADD CONSTRAINT presentation_rrequest_room_request_fk FOREIGN KEY ( id_room_request )
        REFERENCES room_requests ( id_room_request );

ALTER TABLE reservations
    ADD CONSTRAINT reservation_organizer_fk FOREIGN KEY ( organizer_id_organizer )
        REFERENCES organizers ( id_organizer );

ALTER TABLE reservations
    ADD CONSTRAINT reservation_room_fk FOREIGN KEY ( room_id_room )
        REFERENCES rooms ( id_room );

ALTER TABLE reservations
    ADD CONSTRAINT reservation_room_request_fk FOREIGN KEY ( room_request_id_room_request )
        REFERENCES room_requests ( id_room_request )
            ON DELETE CASCADE;

ALTER TABLE rooms
    ADD CONSTRAINT room_location_fk FOREIGN KEY ( location_id_location )
        REFERENCES locations ( id_location );

ALTER TABLE rooms
    ADD CONSTRAINT room_organizer_fk FOREIGN KEY ( organizer_id_organizer )
        REFERENCES organizers ( id_organizer );

ALTER TABLE room_requests
    ADD CONSTRAINT room_request_location_fk FOREIGN KEY ( location_id_location )
        REFERENCES locations ( id_location );

ALTER TABLE room_requests
    ADD CONSTRAINT room_request_organizer_fk FOREIGN KEY ( organizer_id_organizer )
        REFERENCES organizers ( id_organizer );

CREATE OR REPLACE VIEW ORGANIZERS_V ( ID_ORGANIZER, name, email, waiting ) AS
SELECT DISTINCT
  o.ID_ORGANIZER,
  name,
  email,
  CASE WHEN EXISTS
    (
     SELECT * FROM room_requests r
      WHERE r.ID_ORGANIZER = o.ID_ORGANIZER
      AND r.ID_RESERVATION IS NULL
    )
    THEN 'Y'
    ELSE 'N'
  END AS waiting
FROM organizers o
     JOIN room_requests rr
     ON o.ID_ORGANIZER = rr.ID_ORGANIZER 
;

CREATE OR REPLACE VIEW ROOM_REQUESTS_V ( name, email, location, mincapacity, reservationstart, reservationend, reservationlength, vcready, podiumsize ) AS
SELECT
    organizers.name,
    organizers.email,
    locations.name AS location,
    ROOM_REQUESTS.mincapacity,
    ROOM_REQUESTS.reservationstart,
    ROOM_REQUESTS.reservationend,
    ROOM_REQUESTS.reservationlength,
    MEETING_RREQUESTS.vcready,
    PRESENTATION_RREQUESTS.podiumsize
FROM
    ROOM_REQUESTS
    INNER JOIN locations ON locations.id_location = ROOM_REQUESTS.id_location
    INNER JOIN organizers ON organizers.id_organizer = ROOM_REQUESTS.id_organizer,
    MEETING_RREQUESTS,
    PRESENTATION_RREQUESTS 
;

CREATE OR REPLACE VIEW ROOMS_V ( name, capacity, location, availabilitystart, availabilityend, vcready, podiumsize ) AS
SELECT
    rooms.name,
    rooms.capacity,
    locations.name AS "location",
    locations.availabilitystart,
    locations.availabilityend,
    MEETING_ROOMS.vcready,
    PRESENTATION_ROOMS.podiumsize
FROM
         rooms
    INNER JOIN locations ON locations.id_location = rooms.id_location,
    MEETING_ROOMS,
    PRESENTATION_ROOMS 
;

CREATE OR REPLACE VIEW USERS_V ( ID_ORGANIZER, email, credential_type, data, role ) AS
SELECT
	o.ID_ORGANIZER,
	o.email,
	c.credential_type,
	c.data,
	r.name role
FROM ORGANIZERS o 
     JOIN CREDENTIALS c ON o.ID_ORGANIZER = c.ID_ORGANIZER
	JOIN ROLES r ON o.ID_ROLE = r.ID_ROLE
GROUP BY c.credential_type 
;

CREATE OR REPLACE TRIGGER fkntm_reservations BEFORE
    UPDATE OF room_request_id_room_request ON reservations
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table RESERVATIONS is violated');
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_presentation_rooms BEFORE
    INSERT OR UPDATE OF id_room ON presentation_rooms
    FOR EACH ROW
DECLARE
    d VARCHAR2(17);
BEGIN
    SELECT
        a.type
    INTO d
    FROM
        rooms a
    WHERE
        a.id_room = :new.id_room;

    IF ( d IS NULL OR d <> 'PRESENTATION_ROOM' ) THEN
        raise_application_error(-20223, 'FK PRESENTATION_ROOM_ROOM_FK in Table PRESENTATION_ROOMS violates Arc constraint on Table ROOMS - discriminator column type doesn''t have value ''PRESENTATION_ROOM'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_meeting_rooms BEFORE
    INSERT OR UPDATE OF id_room ON meeting_rooms
    FOR EACH ROW
DECLARE
    d VARCHAR2(17);
BEGIN
    SELECT
        a.type
    INTO d
    FROM
        rooms a
    WHERE
        a.id_room = :new.id_room;

    IF ( d IS NULL OR d <> 'MEETING_ROOM' ) THEN
        raise_application_error(-20223, 'FK MEETING_ROOM_ROOM_FK in Table MEETING_ROOMS violates Arc constraint on Table ROOMS - discriminator column type doesn''t have value ''MEETING_ROOM'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_2_meeting_rrequests BEFORE
    INSERT OR UPDATE OF id_room_request ON meeting_rrequests
    FOR EACH ROW
DECLARE
    d VARCHAR2(21);
BEGIN
    SELECT
        a.type
    INTO d
    FROM
        room_requests a
    WHERE
        a.id_room_request = :new.id_room_request;

    IF ( d IS NULL OR d <> 'MEETING_RREQUEST' ) THEN
        raise_application_error(-20223, 'FK MEETING_RREQUEST_ROOM_REQUEST_FK in Table MEETING_RREQUESTS violates Arc constraint on Table ROOM_REQUESTS - discriminator column type doesn''t have value ''MEETING_RREQUEST'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fka_presentation_rrequests BEFORE
    INSERT OR UPDATE OF id_room_request ON presentation_rrequests
    FOR EACH ROW
DECLARE
    d VARCHAR2(21);
BEGIN
    SELECT
        a.type
    INTO d
    FROM
        room_requests a
    WHERE
        a.id_room_request = :new.id_room_request;

    IF ( d IS NULL OR d <> 'PRESENTATION_RREQUEST' ) THEN
        raise_application_error(-20223, 'FK PRESENTATION_RREQUEST_ROOM_REQUEST_FK in Table PRESENTATION_RREQUESTS violates Arc constraint on Table ROOM_REQUESTS - discriminator column type doesn''t have value ''PRESENTATION_RREQUEST'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE SEQUENCE cities_id_city_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cities_id_city_trg BEFORE
    INSERT ON cities
    FOR EACH ROW
    WHEN ( new.id_city IS NULL )
BEGIN
    :new.id_city := cities_id_city_seq.nextval;
END;
/

CREATE SEQUENCE countries_id_country_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER countries_id_country_trg BEFORE
    INSERT ON countries
    FOR EACH ROW
    WHEN ( new.id_country IS NULL )
BEGIN
    :new.id_country := countries_id_country_seq.nextval;
END;
/

CREATE SEQUENCE credentials_id_credential_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER credentials_id_credential_trg BEFORE
    INSERT ON credentials
    FOR EACH ROW
    WHEN ( new.id_credential IS NULL )
BEGIN
    :new.id_credential := credentials_id_credential_seq.nextval;
END;
/

CREATE SEQUENCE locations_id_location_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER locations_id_location_trg BEFORE
    INSERT ON locations
    FOR EACH ROW
    WHEN ( new.id_location IS NULL )
BEGIN
    :new.id_location := locations_id_location_seq.nextval;
END;
/

CREATE SEQUENCE notifications_id_notification START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER notifications_id_notification BEFORE
    INSERT ON notifications
    FOR EACH ROW
    WHEN ( new.id_notification IS NULL )
BEGIN
    :new.id_notification := notifications_id_notification.nextval;
END;
/

CREATE SEQUENCE organizers_id_organizer_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER organizers_id_organizer_trg BEFORE
    INSERT ON organizers
    FOR EACH ROW
    WHEN ( new.id_organizer IS NULL )
BEGIN
    :new.id_organizer := organizers_id_organizer_seq.nextval;
END;
/

CREATE SEQUENCE reservations_id_reservation START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER reservations_id_reservation BEFORE
    INSERT ON reservations
    FOR EACH ROW
    WHEN ( new.id_reservation IS NULL )
BEGIN
    :new.id_reservation := reservations_id_reservation.nextval;
END;
/

CREATE SEQUENCE roles_id_role_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER roles_id_role_trg BEFORE
    INSERT ON roles
    FOR EACH ROW
    WHEN ( new.id_role IS NULL )
BEGIN
    :new.id_role := roles_id_role_seq.nextval;
END;
/

CREATE SEQUENCE room_requests_id_room_request START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER room_requests_id_room_request BEFORE
    INSERT ON room_requests
    FOR EACH ROW
    WHEN ( new.id_room_request IS NULL )
BEGIN
    :new.id_room_request := room_requests_id_room_request.nextval;
END;
/

CREATE SEQUENCE rooms_id_room_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rooms_id_room_trg BEFORE
    INSERT ON rooms
    FOR EACH ROW
    WHEN ( new.id_room IS NULL )
BEGIN
    :new.id_room := rooms_id_room_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             2
-- ALTER TABLE                             38
-- CREATE VIEW                              4
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          15
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         10
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
